### PR TITLE
Remove unused ValueFormatterStore

### PR DESCRIPTION
**Pull request by thiemowmde**
This is a resubmission of #93 without the bits it removes from the still used ValueFormatter class. This is supposed to make reviewing this much easier because #112 focuses on a single class that is not used any more for sure. I will rebase #93 after #112 is merged.

[Bug: T172916](https://phabricator.wikimedia.org/T172916)

### CODE REVIEW

**Comment by Ladsgroup** [comment]
It has conflicts, just FYI :)

**Comment by thiemowmde** [comment]
Thanks for the note! Rebased now.

**Comment by thiemowmde** [comment]
Rebased again after #114.

**Comment by thiemowmde** [comment]
Rebased again.

**Pull request merged**
