### PR TITLE
Remove unused globeCoordinate.Formatter

### PR DESCRIPTION
**Pull request by thiemowmde**
This is blocked by #122 ~~and https://gerrit.wikimedia.org/r/371209~~, and must be rebased after #122 is merged.

[Bug: T172916](https://phabricator.wikimedia.org/T172916)

### CODE REVIEW

**Comment by Ladsgroup** [comment]
So did you rebase on top of #122?

**Comment by lucaswerkmeister** [comment]
I rebased just now, but build is still failing.

**Comment by lucaswerkmeister** [comment]
It works if I restore some tiny `globeCoordinate` object:
```patch
diff --git a/karma.conf.js b/karma.conf.js
index 95c56453bc..d471843d20 100644
--- a/karma.conf.js
+++ b/karma.conf.js
@@ -5,6 +5,7 @@ module.exports = function ( config ) {
 		files: [
 			'node_modules/jquery/dist/jquery.js',
 			'lib/util/util.inherit.js',
+			'lib/globeCoordinate/globeCoordinate.js',
 			'lib/globeCoordinate/globeCoordinate.GlobeCoordinate.js',
 			'src/dataValues.js',
 			'src/DataValue.js',
diff --git a/lib/globeCoordinate/globeCoordinate.js b/lib/globeCoordinate/globeCoordinate.js
new file mode 100644
index 0000000000..b3bc44fd43
--- /dev/null
+++ b/lib/globeCoordinate/globeCoordinate.js
@@ -0,0 +1 @@
+this.globeCoordinate = {};
```

**Comment by thiemowmde** [comment]
Yea, that module was used as a namespace definition. I think restoring it like you suggested is the most easy solution for now.

**Comment by Ladsgroup** [comment]
It's not WIP anymore, right?

**Comment by lucaswerkmeister** [comment]
Not anymore, I think, yes.

**Pull request merged**
