### PR TITLE
Remove unused getSortKey from DataValue interface

### PR DESCRIPTION
**Pull request by thiemowmde**
I'm trying to minimize the unused code in this repository for years. Today I finally found a string I can pull without the whole thing breaking apart: Just do a fultext search for "getSortKey" and you will see it is not used anywhere.

This will allow us to remove much, much more unused code. I'm focusing on two very small methods here and plan to continue removing more unused code in later patches.

* The iso6709 method on the class is unused now. Note there is an other static helper function with the same name and a parameter. That is still used.
* _getTimestamp is private anyway. The parameter is unused now.

After this is merged and released, the following patches also must be merged:
* https://github.com/wmde/WikibaseDataModelJavaScript/pull/74

[Bug: T172916](https://phabricator.wikimedia.org/T172916)

### CODE REVIEW

**Comment by Ladsgroup** [comment]
Now it has conflicts :/ I also would like some time for more eyes on this as it's a little bit big (but looks trivial)

**Comment by thiemowmde** [comment]
Rebased.

**Comment by thiemowmde** [comment]
Rebased again after #114.

**Comment by thiemowmde** [comment]
@Ladsgroup, do you have time to look at this again? Also #118? Thanks!

**Comment by thiemowmde** [comment]
Rebased again.

**Pull request merged**
