### PR TITLE
Prepare the library for relasing as a npm package

### PR DESCRIPTION
**Pull request by manicki**
This is a part of https://phabricator.wikimedia.org/T177232.
Once this is merged, I am going to tag 1.0.0 release and publish it as a npm package called `wikibase-data-values` (alternative name suggestions should be preferably submitted before creating the npm package!).

### CODE REVIEW

**Comment by thiemowmde** [comment]
"wikibase-data-values" sound to generic. It's an entire concept that's named "DataValues", and part of the Wikibase software. Please use a more specific name.

Also I wonder how this code is going to be used, now that the ResourceLoader definitions are gone.

**Comment by manicki** [comment]
What alternative name you suggest then?

**Comment by thiemowmde** [comment]
"data-values/javascript" was the Composer name. I'm afraid I don't get why we need to shift away from what we had there?

**Comment by manicki** [comment]
It is a javascript library, so I find this part not needed.
As far as I understand, npm convention for naming packages does not follow this "org/package" scheme.
That would mean it would just be "data-values". Fine with me, but really generic name IMO, therefore I added wikibase prefix.
What do you suggest instead?

**Comment by thiemowmde** [comment]
I found it a good idea to stick to the existing name, and possibly make it "datavalues-javascript", or maybe "wikibase-datavalues-javascript".

I looked the NPM documentation up and found the suggestion to *not* add "js" to package names. So we end with "wikibase-datavalues", either without or with the additional dash.

**Comment by manicki** [comment]
Right, so "wikibase-data-values" (as currently is the name) or ""wikibase-datavalues" then?

I personally don't like "datavalues", but I am not going to object it if that's what people want.

**Comment by manicki** [comment]
Regarding the RL module part of you comment
> Also I wonder how this code is going to be used, now that the ResourceLoader definitions are gone.

I am going to have Wikibase defines resource loader module it uses/needs. This should not belong to the library itself IMO.

**Comment by thiemowmde** [comment]
Thanks for the responses, that was very helpful for me.

Let's stick to "…-data-values" with dashes then. That dash was there before.

**Pull request merged**
